# Generated by Django 5.0.3 on 2026-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_alter_voter_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentofficer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
