# Generated by Django 5.0.3 on 2026-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
